<a href="https://colab.research.google.com/github/Russel-hunho/DeepLearning/blob/main/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

(https://wikidocs.net/52415)
# 파이토치 기본

### 1. 파이토치 패키지

In [2]:
import torch
  # main
import torch.autograd
  # 자동 미분 기능
import torch.nn
  # 신경망 구축을 위한 다양한 데이터구조, 레이어 등이 정의됨
    # RNN, LSTM 등의 레이어 / ReLU 등의 활성화함수 / MSELoss 등의 손실함수
import torch.optim
  # SGD(Stochastic Gradient Descent, 확률적 경사 하강법) 중심의, 파라미터 최적화 알고리즘 구현
import torch.utils.data
  # SGD의 반복연산을 실행할 때 사용하는 미니 배치용 유틸리티 함수 포함
import torch.onnx
  # ONNX(Open Neural Network Exchange) 포맷.
    # 모델을 export할 때 사용됨, 서로다른 딥 러닝 프레임워크 간 모델 공유 시에 사용




### 2. 텐서 조작하기 1

[example]
1. 2D Tensor for Simple Setting

  |t| = (Batch size, dim)
2. 3D Tensor for 컴퓨터비전

  |t| = (Batch size, width, height)
3. 3D Tensor for 자연어 처리(NLP)

  |t| = (Batch size, length, dim)
        lenght = 문장길이
        dim = 단어 벡터의 차원


In [3]:
''' NLP 3D Tensor 변환 이해하기 '''
## 1차원 입력 raw data
A = ["나는 사과를 좋아해", "나는 바나나를 좋아해", "나는 사과를 싫어해", "나는 바나나를 싫어해"]

## 2D로 변환 for 단어 구분
  # 4x3 2D Tensor
B = [["나는", "사과를", "좋아해"],
 ["나는", "바나나를", "좋아해"],
  ["나는", "사과를", "싫어해"],
  ["나는", "바나나를", "싫어해"]]

## 각 단어를 vector로 변환하여, 3D로 변환
'''
  '나는' = [0.1, 0.2, 0.9]
  '사과를' = [0.3, 0.5, 0.1]
  '바나나를' = [0.3, 0.5, 0.2]
  '좋아해' = [0.7, 0.6, 0.5]
  '싫어해' = [0.5, 0.6, 0.7]
'''
C = [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

## Batch size=2 로, Data 구분
Batch1 = [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
         [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]
Batch2 = [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
         [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]


In [4]:
''' Numpy로 Tensor 만들기 '''

import numpy as np

# 1D
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)
print("Rank of t: ", t.ndim)
print("Shape of t: ", t.shape, end="\n\n")

print("t[0] t[1] t[-1] = ", t[0], t[1], t[-1])
  #slicing 
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])
print('t[:2] t[3:]     = ', t[:2], t[3:], end="\n\n\n")

# 2D
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

[0. 1. 2. 3. 4. 5. 6.]
Rank of t:  1
Shape of t:  (7,)

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank  of t:  2
Shape of t:  (4, 3)


In [5]:
''' PyTorch로 Tensor 만들기 '''

import torch

## 1D
t = torch.FloatTensor( [0., 1., 2., 3., 4., 5., 6. ] )
print(t)
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # size = shape
print(type(t), end="\n\n")

print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

## 2D
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])
print(t)
print(t.dim())  # rank. 즉, 차원
print(t.size(), end = "\n\n") # shape

print(t[:,1])
print(t[:,1].size())




tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
<class 'torch.Tensor'>

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [6]:
'''브로드캐스팅'''
## 사칙연산을 위해 두 행렬의 크기를 자동으로 맞춰 연산

## 1. 같은 크기의 두 tensor일 경우
m1 = torch.FloatTensor( [[3,3]] )
m2 = torch.FloatTensor( [[2,2]] )
print(m1+m2, end = "\n\n")

## 2. 다른 크기의 두 Tensor일 경우

# 2.1. vector + scalar: scalar가 vector size에 맞게 복제됨
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1+m2, end = "\n\n")

# 2.2. 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # [[1,2]] -> [[1,2],[1,2]]
m2 = torch.FloatTensor([[3], [4]]) # [[3],[4]] -> [[3,3], [4,4]]
print(m1+m2, end = "\n\n")

tensor([[5., 5.]])

tensor([[4., 5.]])

tensor([[4., 5.],
        [5., 6.]])



In [7]:
''' 행렬곱셈(matmul)과 곱셈(*)의 차이'''

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print("")

## 행렬곱셈(matmul):
print(m1.matmul(m2)) # 2 x 1
print("")

## 곱셈(*):
print(m1 * m2) # 2 x 2
  # m2가 m1 size에 맞게 브로드캐스팅 된 후, 같은 위치의 값들끼리만 곱해짐
print(m1.mul(m2)) # 같은 결과

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])

tensor([[ 5.],
        [11.]])

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [8]:
''' 다양한 연산 '''

## 평균
t = torch.FloatTensor([1,2])
print(t.mean())
print(int(t.mean()), end="\n\n")

t = torch.FloatTensor([[1,2],[3,4]])
print(t.mean()) # 전체 원소의 평균
print(t.mean(dim=0)) # 첫번째 차원(행)을 제거, 각 열의 평균을 구함
print(t.mean(dim=1)) # 두번째 차원(열)을 제거, 각 행의 평균을 구함
print(t.mean(dim=-1)) # 마지막 차원(=두번째=열)을 제거, 각 행의 평균을 구함
try: print(t.mean(dim=2))
except:  print("Fail")
print()

## 덧셈
t = torch.FloatTensor([[1,2],[3,4]])
print(t.sum()) # 전체 합
print(t.sum(dim=0)) # 행 제거
print(t.sum(dim=1)) # 열 제거
print(t.sum(dim=-1)) # 열 제거
print()

## 최댓값(Max), 아그맥스(ArgMax)
t =torch.FloatTensor( [[1,2],[3,4]] )
print(t.max()) # 전체의 최댓값
print(t.max(dim=0)) # 행 제거
  # 1. "각 열의 최댓값"(max) + 2. "각 열 최댓값의 위치(행 값)"(ArgMax) 반환
print("Max: ", t.max(dim=0)[0]) # 각 열의 최댓값만
print("ArgMax: ", t.max(dim=0)[1]) # 각 열의 argmax만
print(t.argmax()) #전체 최댓값의 위치. 0,1,2,3중 4가 위치한 3
print(t.argmax(dim=0))

tensor(1.5000)
1

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])
Fail

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
ArgMax:  tensor([1, 1])
tensor(3)
tensor([1, 1])


### 3. 텐서 조작하기 2

In [9]:
''' View '''
## 원소의 수를 유지하면서, Tensor의 크기&차원을 변경
## Numpy의 Reshape 기능

t = np.array([[ [0,1,2], [3,4,5] ],
              [ [6,7,8], [9,10,11] ]])
ft = torch.FloatTensor(t)

print(ft.shape, end="\n\n")
  #(2,2,3)

# 3차원에서 2차원으로 변경
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape, end="\n\n")
  # 총 원소의 개수는 항상 유지됨!
  # size를 -1로 설정시, 다른 차원으로부터 해당 값을 유추한다!

# (2,2,3)->(?,1,3)
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape, end="\n\n")

torch.Size([2, 2, 3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])



In [14]:
''' 스퀴즈(Squeeze)'''
## 1인 차원을 제거한다

ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape, end="\n\n")

print(ft.squeeze())
print(ft.squeeze().shape, end="\n\n\n")

''' 언스퀴즈(Unsqueeze)'''
## 특정 위치에 1인 차원을 추가한다

ft = torch.FloatTensor([0,1,2])
print(ft.shape, end="\n\n")

# Case1
print(ft.unsqueeze(0)) # 0번째 index = 1번째 차원에 추가
print(ft.unsqueeze(0).shape)

# Case2
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape, end="\n\n")

''' view로 unsqueeze 구현 '''
# Case1
print(ft.view(1,-1))
print(ft.view(1,-1).shape)
#Case2
print(ft.view(-1,1))
print(ft.view(-1,1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])

tensor([0., 1., 2.])
torch.Size([3])


torch.Size([3])

tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])

tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [17]:
'''타입 캐스팅(Type Casting)'''
lt = torch.LongTensor([1,2,3,4]) # long타입 Tensor 선언
print(lt)
print(lt.float()) # float형으로 변경

bt = torch.ByteTensor([True, False, False, True]) # Byte 타입

print(bt)
print(bt.long())
print(bt.float())

'''소수'''
# Float: 32 bit floating point
t = torch.FloatTensor([1])
# Double: 64 bit floating point
t = torch.DoubleTensor([1])
# Half: 16 bit floating point
t = torch.HalfTensor([1])
'''정수'''
# Int: 32 bit integer
t = torch.IntTensor([1])
# Long: 64 bit integer
t = torch.LongTensor([1])
# Short: 16 bit integer
t = torch.ShortTensor([1])
# Char: 8 bit signed integer
t = torch.CharTensor([1])
# Byte: 8 bit unsigned integer
t = torch.ByteTensor([1])

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [23]:
'''연결하기(concatenate)'''
## torch.cat([A,B,C])

x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

print(torch.cat([x,y],dim = 0)) # 첫번째 차원을 늘려라 -> [4,2]가 된다
print(torch.cat([x,y],dim = 1)) # 두번째 차원을 늘려라 -> [2,4]가 된다
print()

x = torch.FloatTensor([[1,2],[3,4]]) # [2,2]
y = torch.FloatTensor([[5,6],[7,8],[9,10]]) # [3,2]

print(torch.cat([x,y],dim = 0)) # 첫번째 차원을 늘려라 -> [5,2]가 된다
try:
  print(torch.cat([x,y],dim = 1)) # 두번째 차원을 늘려라 -> 두번째 차원의 길이가 달라 실패
except:
  print("Fail")

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
Fail


In [27]:
'''스택킹(Stacking)'''
## torch.stack([A,B,C,....])
## A,B,C를 쭉 쌓는다

x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x,y,z]))
# 동작 원리는 하기와 같다
print( torch.cat( [ x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0) ] , dim = 0 ) )

x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5, 7])
z = torch.FloatTensor([3, 6, 8, 9])
try: print(torch.stack([x,y,z])) # 역시 길이가 달라 실패
except: print("Fail")

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
Fail


In [30]:
'''ones_like와 zeros_like'''
# 1로 채워진 텐서
# 0으로 채워진 텐서


x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

# x와 같은 크기의, 모든 원소가 1로 채워져있는 Tensor 반환
print(torch.ones_like(x))
# x와 같은 크기의, 모든 원소가 0으로 채워져있는 Tensor 반환
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [29]:
'''In-place Operation (덮어쓰기 연산)'''
## 연산에 _를 붙이면, 연산 결과가 대상에 덮어써진다!

x = torch.FloatTensor([[1, 2], [3, 4]])

# 평범한 연산
print(x.mul(2.))
print(x, end="\n\n")
  # x.mul 이후에도, x에는 원래 값이 그대로 남아있다

# 덮어쓰기 연산
print(x.mul_(2.))
print(x)


tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### 4. 파이썬 클래스

4.1. 함수


In [31]:
''' 함수로 덧셈기 구현'''

result = 0 # 전역변수 선언

def add(num):
  global result
  result += num
  return result

print(add(3))
print(add(4))

3
7


4.2. 클래스(Class)

In [34]:
''' Class로 덧셈기 구현'''

class Calculator:
  # 생성자 선언
  def __init__(self):
    self.result = 0

  def add(self,num):
    self.result += num
    return self.result

cal1 = Calculator()
cal2 = Calculator()
print(cal1.result)
print(cal2.result, end="\n\n")

print(cal1.add(3))
print(cal2.add(4))

0
0

3
4
