<a href="https://colab.research.google.com/github/Russel-hunho/DeepLearning/blob/main/pytorch_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://wikidocs.net/53545

#1. 선형 회귀(Linear Regression)

1. 가설(Hypothesis) 수립: y = H(x)
      
      선형회귀에선, H(x) = Wx+b
      (W: 가중치, b: 편향(Bias))
2. 비용함수(Cost Function) 설정 -> 최소화 하기
3. 최적화 알고리즘 선택
4. 손실 계산(Compute Loss)

비용 함수(cost function) = 손실 함수(loss function) = 오차 함수(error function) = 목적 함수(objective function)

옵티마이저(Optimizer) 알고리즘 = 최적화 알고리즘

*   경사 하강법(Gradient Descent)
*   항목 추가



### 경사 하강법(Gradient Descent)
가설: y = H(x) = Wx


In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [21]:
## 항상 같은 결과가 나오도록 seed값 고정시키기
torch.manual_seed(1)

In [22]:
''' [y = Wx + b] model을 학습시킬 data 설정 ''' 

# 변수 선언
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [23]:
''' 가설에 사용할 가중치, 편향값의 초기값 설정'''

# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True) 
# 가중치 W를 출력
print(W)

b = torch.zeros(1, requires_grad=True)
print(b)

# 현재 H(x) = 0*x + 0

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [24]:
''' 가설 세우기 '''

hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [25]:
''' 비용함수 선언 '''

# 이번 선형회귀에선, 오차의 평균제곱으로 설정
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [26]:
''' 경사하강법 구현 '''
## SGD: 경사 하강법의 일종

optimizer = optim.SGD([W, b], lr=0.01)
  # lr: 학습률(Learning Rate)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [27]:
# gradient를 0으로 초기화
optimizer.zero_grad()
print(optimizer)
# 비용 함수를 미분하여 gradient 계산
cost.backward()
print(cost)
# W와 b를 업데이트
optimizer.step()
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
tensor(18.6667, grad_fn=<MeanBackward0>)
SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


전체 실행 코드

In [31]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

## 항상 같은 결과가 나오도록 seed값 고정시키기
torch.manual_seed(1)

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 3500 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/3500 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/3500 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/3500 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/3500 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/3500 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/3500 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/3500 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/3500 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/3500 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/3500 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/3500 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/3500 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/3500 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/3500 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/3500 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/3500 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/3500 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/3500 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/3500 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/3500 W: 1.997, b: 0.008 Cost: 0.000008

#2. 자동 미분(Autograd)

파이토치는 자동 미분(Autograd) 기능을 제공한다!

In [1]:
import torch

w = torch.tensor(2.0, requires_grad = True) # 스칼라 tensor
  # requires_grad = True: 이 텐서에 대한 기울기를 저장하겠다!
    # w.grad에, w에 대한 미분값이 저장된다.

# 수식 정의
y = w**2
z = 2*y + 5

# z의 w에 대한 기울기 계산
z.backward()
  # 결과는 w.grad에 저장된다!
  # z를 w로 편미분한 후, w=2.0 값을 대입함
print("수식을 w로 미분한 값: {}".format(w.grad))

수식을 w로 미분한 값: 8.0


#3. 다중 선형 회귀(Multivariable Linear Regression)

다수의 x로부터 y를 예측하자

H(x) = w1*x1 + w2*x2 + w3*x3 + b


### 3.1. 스칼라형 다변수 x1,x2,x3에 대한 다중 선형 회귀로 풀기

In [2]:
import torch
import torch.nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed((1)) # seed 고정

In [3]:
# 훈련 Data
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [4]:
# 가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [9]:
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5) # SGD모델, 학습률 = 1e-5

nb_epochs = 1000 # 반복횟수
for epoch in range(nb_epochs + 1):

  # H(X) 계산
  hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

  # cost 계산 (에러 제곱 평균)
  cost = torch.mean((hypothesis - y_train) ** 2)

  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward() # w1, w2, w3, b로 각각 편미분
  optimizer.step()

  # 100번마다 로그 출력
  if epoch % 100 == 0:
    print("Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}".format(
        epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
    ))



Epoch    0/1000 w1: 0.757 w2: 0.571 w3: 0.682 b: 0.011 Cost: 0.753650
Epoch  100/1000 w1: 0.761 w2: 0.568 w3: 0.682 b: 0.011 Cost: 0.729680
Epoch  200/1000 w1: 0.764 w2: 0.564 w3: 0.682 b: 0.011 Cost: 0.706930
Epoch  300/1000 w1: 0.767 w2: 0.561 w3: 0.682 b: 0.011 Cost: 0.685357
Epoch  400/1000 w1: 0.770 w2: 0.558 w3: 0.682 b: 0.011 Cost: 0.664896
Epoch  500/1000 w1: 0.773 w2: 0.555 w3: 0.682 b: 0.011 Cost: 0.645467
Epoch  600/1000 w1: 0.776 w2: 0.552 w3: 0.682 b: 0.011 Cost: 0.627032
Epoch  700/1000 w1: 0.779 w2: 0.549 w3: 0.682 b: 0.012 Cost: 0.609540
Epoch  800/1000 w1: 0.782 w2: 0.546 w3: 0.682 b: 0.012 Cost: 0.592941
Epoch  900/1000 w1: 0.785 w2: 0.543 w3: 0.682 b: 0.012 Cost: 0.577177
Epoch 1000/1000 w1: 0.788 w2: 0.540 w3: 0.682 b: 0.012 Cost: 0.562214


### 3.2. 행렬 변수 X에 대한 선형 회귀로 풀기

H(X) = W*X + B

W = [W1,W2,W3]

X = [[x11, x12, x13], [x21, x22, x23],[x31, x32, x33]]

B = [b b b]

In [10]:
# 훈련 Data
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [12]:
# 가중치와 편향 선언
W = torch.zeros((3,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [16]:
# Optimizer 설정
optimizer = optim.SGD([W,b], lr = 1e-5)

nb_epochs = 100
for epoch in range(nb_epochs+1):

  # H(x) 계산
  hypothesis = x_train.matmul(W)+b

  # cost 계산
  cost = torch.mean((hypothesis-y_train)**2)

  # cost로 H(x) 개선
  optimizer.zero_grad() # gradient를 0으로 초기화
  cost.backward() # 미분
  optimizer.step()

  #10번마다 출력
  if epoch % 10 == 0: 
    print("Epoch {:4d}/{} hypothesis: {} Cost: {:6f}".format(
        epoch, nb_epochs, hypothesis, cost
    ))



Epoch    0/100 hypothesis: tensor([[154.0430],
        [185.0920],
        [175.8333],
        [198.5690],
        [141.2222]], grad_fn=<AddBackward0>) Cost: 5.749629
Epoch   10/100 hypothesis: tensor([[154.0415],
        [185.0892],
        [175.8437],
        [198.5632],
        [141.2229]], grad_fn=<AddBackward0>) Cost: 5.724895
Epoch   20/100 hypothesis: tensor([[154.0399],
        [185.0863],
        [175.8540],
        [198.5574],
        [141.2235]], grad_fn=<AddBackward0>) Cost: 5.700261
Epoch   30/100 hypothesis: tensor([[154.0384],
        [185.0836],
        [175.8643],
        [198.5517],
        [141.2241]], grad_fn=<AddBackward0>) Cost: 5.675793
Epoch   40/100 hypothesis: tensor([[154.0368],
        [185.0808],
        [175.8746],
        [198.5459],
        [141.2247]], grad_fn=<AddBackward0>) Cost: 5.651419
Epoch   50/100 hypothesis: tensor([[154.0353],
        [185.0780],
        [175.8848],
        [198.5402],
        [141.2253]], grad_fn=<AddBackward0>) Cost: 5.62714

#4. nn.Module로 선형 회귀 구현

nn.Module을 통해 더 쉽게 선형 회귀를 구현할 수 있다!

1. nn.Linear() 로 선형 회귀 모델 구현

         model = nn.Linear(input_dim, output_dim)
2. nn.functional.mse_loss()로 평균제곱오차 구현

         Cost = F.mse_loss(prediction, y_train)

### 4.1. nn.Module로 단순선형회귀 구현

In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [18]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [25]:
# 모델 선언
# model = nn.Linear(input_dim, output_dim)
  # input_dim: 입력 차원, x의 개수
  # output_dim: 출력 차원, y의 개수

# 단순 선형 회귀 이므로, input_dim = 1; output_dim = 1;
torch.manual_seed(1)
model = nn.Linear(1,1)
print(list(model.parameters()))
  # W, b가 순서대로 출력된다
  # 현재 print되어 나오는 값은 랜덤값! (seed 고정)

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [27]:
# Oprimizer 설정; SGD 사용
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [29]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

  # H(x) 계산
  prediction = model(x_train)

  # cost 계산
  cost = F.mse_loss(prediction, y_train)
    # torch.nn.functional에 있는 내장함수; 오차제곱평균(mse: mean square Error)

  # cost로 H(x) 개선
  optimizer.zero_grad() # 미분값 초기화
  cost.backward() # 미분값 계산
  optimizer.step() # w,b 업데이트

  #100번마다 출력
  if epoch%100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [31]:
## 학습 완료된 model의 결과 data 확인

# x = 4.0
new_var = torch.FloatTensor([[4.0]])

pred_y = model(new_var) # forward 연산
print("훈련 후 입력이 4일 때의 예측 값: ", pred_y, end="\n\n")

# y = 2*x로, 8이 나와야 함!
# 7.9989 -> 잘 근접함!

# W,b 값 출력
print(list(model.parameters()))

훈련 후 입력이 4일 때의 예측 값:  tensor([[7.9989]], grad_fn=<AddmmBackward0>)

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


### 4.2. nn.Module로 다중선형회귀 구현

In [34]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# x1,x2,x3 -> y

In [37]:
# model 선언
torch.manual_seed(1)
model = nn.Linear(3,1) # x 3개, y 1개

print(list(model.parameters()))
  # w1,w2,w3,b 출력됨

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [39]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs+1):

  # H(x)
  prediction = model(x_train)

  # Cose
  cost = F.mse_loss(prediction, y_train)

  # cost로 H 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  #100번마다 로그 출력
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
      epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [44]:
# 모델 결과 확인

test_var = torch.FloatTensor([[73,80,75]])
pred_y = model(test_var)
print("훈련 후 입력 [73,80,75]에 대한 y 예측값: ", float(pred_y))
print()
print(list(model.parameters()))

훈련 후 입력 [73,80,75]에 대한 y 예측값:  151.2305450439453

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


#5. 클래스로 파이토치 모델 구현하기