<a href="https://colab.research.google.com/github/Russel-hunho/DeepLearning/blob/main/pytorch_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. 선형 회귀(Linear Regression)

1. 가설(Hypothesis) 수립: y = H(x)
      
      선형회귀에선, H(x) = Wx+b
      (W: 가중치, b: 편향(Bias))
2. 비용함수(Cost Function) 설정 -> 최소화 하기
3. 최적화 알고리즘 선택
4. 손실 계산(Compute Loss)

비용 함수(cost function) = 손실 함수(loss function) = 오차 함수(error function) = 목적 함수(objective function)

옵티마이저(Optimizer) 알고리즘 = 최적화 알고리즘

*   경사 하강법(Gradient Descent)
*   항목 추가



### 경사 하강법(Gradient Descent)
가설: y = H(x) = Wx


In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [21]:
## 항상 같은 결과가 나오도록 seed값 고정시키기
torch.manual_seed(1)

In [22]:
''' [y = Wx + b] model을 학습시킬 data 설정 ''' 

# 변수 선언
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [23]:
''' 가설에 사용할 가중치, 편향값의 초기값 설정'''

# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True) 
# 가중치 W를 출력
print(W)

b = torch.zeros(1, requires_grad=True)
print(b)

# 현재 H(x) = 0*x + 0

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [24]:
''' 가설 세우기 '''

hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [25]:
''' 비용함수 선언 '''

# 이번 선형회귀에선, 오차의 평균제곱으로 설정
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [26]:
''' 경사하강법 구현 '''
## SGD: 경사 하강법의 일종

optimizer = optim.SGD([W, b], lr=0.01)
  # lr: 학습률(Learning Rate)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [27]:
# gradient를 0으로 초기화
optimizer.zero_grad()
print(optimizer)
# 비용 함수를 미분하여 gradient 계산
cost.backward()
print(cost)
# W와 b를 업데이트
optimizer.step()
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
tensor(18.6667, grad_fn=<MeanBackward0>)
SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


전체 실행 코드

In [31]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

## 항상 같은 결과가 나오도록 seed값 고정시키기
torch.manual_seed(1)

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 3500 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/3500 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/3500 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/3500 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/3500 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/3500 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/3500 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/3500 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/3500 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/3500 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/3500 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/3500 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/3500 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/3500 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/3500 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/3500 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/3500 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/3500 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/3500 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/3500 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/3500 W: 1.997, b: 0.008 Cost: 0.000008